### PR TITLE
Fix for #163

### PR DESCRIPTION
**Pull request by wcwitt**
I cherry-picked @jameskermode fix from #152 onto master, and it appears to address #163. Would someone please double-check and merge?

### CODE REVIEW

**Comment by wcwitt** [comment]
Resolves #163.

**Comment by cortner** [comment]
failing on mac again, but passing locally, so I am merging

**Comment by cortner** [comment]
tagged as JuLIP@0.14.1

**Comment by jameskermode** [comment]
I've attempted a fix at the failing tests, look to be due to a recent numpy change.

**Comment by jameskermode** [comment]
(No need for a new release if/when this passes, only affects CI. I've also dropped tested on 1.7 and added latest Julia nightly instead, and also added Windows which will likely fail the first time)

**Pull request merged**
