### PR TITLE
WIP first attempt at GHA workflow

### PR DESCRIPTION
**Pull request by jameskermode**

### CODE REVIEW

**Comment by cortner** [comment]
I guess we then have to merge this into the other PR as well, yes?

**Comment by jameskermode** [comment]
or once this works and we merge it I can rebase the other one on master

**Comment by jameskermode** [comment]
I think the CI infrastructure is now working correctly, but there are two failing tests:

- Assertion failed at `testpotentials.jl:31`, see https://github.com/JuliaMolSim/JuLIP.jl/runs/3284375027?check_suite_focus=true#step:8:494
- MethodError at `testhessian.jl:111`, see https://github.com/JuliaMolSim/JuLIP.jl/runs/3284375027?check_suite_focus=true#step:8:992

Would you be able to have a look? Could be fixed separate to this PR, but probably cleanest to get everything passing here and then merge.

**Comment by jameskermode** [comment]
Can easily modify the matrix of Julia versions and OSs: currently it's 1.6 and latest nightly build on Ubuntu and MacOS.

**Comment by jameskermode** [comment]
The `testpotentials.jl` failure looks OK to fix by replacing `==` with `≈`, check you're happy with that. The `testhessian.jl` one looks to be something to do with ForwardDiff and Dierckx, so may go away when #140 is merged.

**Comment by jameskermode** [comment]
Just the Dierckx AD Hessian failure now, so I'll merge this branch into #140 and if that passes then we can merge this one

**Comment by cortner** [comment]
nightly should be allowed failures or even just remove those tests

**Comment by jameskermode** [comment]
Merged into #140, so closing this PR.

**Pull request closed without merging**
