### PR TITLE
Fixes for issues #149 and #151

### PR DESCRIPTION
**Pull request by jameskermode**
This PR resolves issues #149 and #151

### CODE REVIEW

**Comment by jameskermode** [comment]
@cortner I set the destination for this PR to dev-v0.11 branch. Not sure if master should be updated as well?

**Comment by wcwitt** [comment]
If you update master, would you please also fix this there too

https://github.com/JuliaMolSim/JuLIP.jl/commit/fb011cdca284aa3bdce793a8d3ab9d9a35378f3e#commitcomment-69381368

**Comment by cortner** [comment]
ok - can merge for now and revisit for master only if we run into this again. Maybe better to focus on getting rid of JuLIP altogether.

**Comment by cortner** [comment]
@wcwitt - sorry I missed your comment, I'll try to bring it in later.

**Comment by wcwitt** [comment]
Thanks both!

**Pull request merged**
